# Generated by Django 5.1.15 on 2026-06-20 11:13

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name="To'liq ism")),
                ('role', models.CharField(max_length=120, verbose_name='Lavozim')),
                ('tagline', models.CharField(max_length=200, verbose_name='Shior (hero)')),
                ('bio', models.TextField(verbose_name='Bio / about')),
                ('avatar', models.ImageField(blank=True, upload_to=core.validators.UUIDImagePath('profile'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.ImageSizeValidator()], verbose_name='Avatar')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Manzil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Sayt profili',
                'verbose_name_plural': 'Sayt profili',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'nikma kategoriyasi",
                'verbose_name_plural': "Ko'nikma kategoriyalari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name="To'liq tavsif")),
                ('cover_image', models.ImageField(blank=True, upload_to=core.validators.UUIDImagePath('projects'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.ImageSizeValidator()], verbose_name='Muqova rasmi')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo havola')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repozitoriy havola')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan (bosh sahifa)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_projects', to='blog.blogpost', verbose_name="Bog'liq maqola (ixtiyoriy)")),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Texnologiya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='core.project')),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Yorliq')),
                ('value', models.CharField(help_text="Raqam (masalan 12) bo'lsa animatsiya bilan sanaladi; matn (UZ) statik.", max_length=20, verbose_name='Qiymat')),
                ('suffix', models.CharField(blank=True, help_text='Masalan: +', max_length=10, verbose_name='Suffiks')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_stats', to='core.siteprofile')),
            ],
            options={
                'verbose_name': "Hero ko'rsatkich",
                'verbose_name_plural': "Hero ko'rsatkichlar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=120, verbose_name='Lavozim')),
                ('organization', models.CharField(max_length=120, verbose_name='Tashkilot')),
                ('period', models.CharField(help_text='Masalan: 2023 — HOZIR', max_length=60, verbose_name='Davr')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_current', models.BooleanField(default=False, verbose_name='Hozirgi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.siteprofile')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Tajribalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('level', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Daraja (0–100)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=60, verbose_name='Platforma')),
                ('url', models.URLField(verbose_name='Havola')),
                ('icon_key', models.CharField(blank=True, help_text='Masalan: github, telegram, linkedin, email', max_length=40, verbose_name='Ikona kaliti')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.siteprofile')),
            ],
            options={
                'verbose_name': 'Ijtimoiy havola',
                'verbose_name_plural': 'Ijtimoiy havolalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
