# Generated by Django 5.1.15 on 2026-06-20 11:13

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog kategoriyasi',
                'verbose_name_plural': 'Blog kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(max_length=300, verbose_name='Qisqa matn (excerpt)')),
                ('body', models.TextField(verbose_name='Matn')),
                ('cover_image', models.ImageField(blank=True, upload_to=core.validators.UUIDImagePath('blog'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.ImageSizeValidator()], verbose_name='Muqova rasmi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan')], default='draft', max_length=10, verbose_name='Holat')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Blog maqolasi',
                'verbose_name_plural': 'Blog maqolalari',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
